### ISSUE TITLE
.rmapi config file not found

### ISSUE THREAD

**Issue by KarmaMonk** [jlarriba/astounding#2]
I found the config file for rmapi under
~/.config/rmapi/rmapi.conf   
not under
~/.rmapi

Thx for your app

**Comment by jlarriba** [comment]
The file that the application reads is the one rmapi uses to store the tokens. This file can be set by an environment variable, but by default is `~/.rmapi` as stated in the [rmapi Github repo](https://github.com/juruen/rmapi):

_RMAPI_CONFIG: filepath used to store authentication tokens. When not set, rmapi uses the file .rmapi in the home directory of the current user._

Maybe you changed it in your environment?

**Comment by errotu** [comment]
Thanks for the great work!
I have the same issue on Ubuntu 20.10. I have not (consciously) changed the anything in my environment.

**Comment by Nachasic** [comment]
I've managed to get it working without tinkering with env. variables, by using a sym link:
```bash
ln -s ~/.config/rmapi/rmapi.conf ~/.rmapi   
```

**Comment by jlarriba** [comment]
As this is a matter of finding where rmapi is locating the .rmapi file with the credentials, which seems to be in two well known locations:

~/.rmapi
~/.config/rmapi/rmapi.conf

I will close the issue.
