### ISSUE TITLE
make a real tuto

### ISSUE THREAD

**Issue by andrelec1** [jlarriba/astounding#3]
You can't have 3 line that say my soft use a wierd api for connecte to the cloud so you need to install and lunch the obsucre sub app for making my app working ....

I think Remarkable have more and more people to use it, and i think lot of theme can't understand how can we get the f**king .rmapi ...

( and for the fun the github rmapi speak about docker ... so for a basique user this isn't acceptable ... ) 

Two solution ... 
 - Make a very simple tuto with ALL command for stupid user that juste need to copy/past in terminal without understanding ...
  OR  Include the login in your app !

**Comment by jlarriba** [comment]
Hi,

thank you for your contribution. You are completely right in your demands, but you need to notice that this is an open source and free project developed on my spare time and it is offered as-is, without any guarantees or promises. For the moment, it is in version 0.3 and, as such, it is more intended to developers and tech-savvy people than to final users.

If you want to solve some of the issues you raise on your comment, please feel free to send PRs.

**Comment by andrelec1** [comment]
#4

**Comment by jlarriba** [comment]
Thanks!

Much appreciated, I have merged your changes.
